# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.2

jobs:
  publish:
    <<: *defaults
    docker:
      - image: circleci/node:16.10
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - yarn-run: build
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          <<: *defaults
          name: Typescript
          yarn-run: build
          version: "16.10"
          pkg-manager: yarn
          persist_to_workspace:
            root: ~/repo
            paths: .
      - test:
          <<: *defaults
          name: Jest
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: "16.10"
          pkg-manager: yarn
      - publish:
          requires:
            - "build"
          filters:
            branches:
              only: 
                - master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
